openapi: 3.0.3
info:
  title: Parameterübergabe mit GET und POST
  description: Parameterübergabe mit GET und POST
  contact:
    email: wichmann@bbs-os-brinkstr.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '0.1'
servers:
  - url: http://127.0.0.1:5000
paths:
  /todo-list/{list_id}:
    get:
      summary: TodoList anzeigen
      description: ...
      operationId: getList
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list' 
        '404':
          description: Fehlerhafte ID
    delete:
      summary: TodoList löschen
      description: ...
      operationId: deleteList
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: TodoList gelöscht
        '404':
          description: Fehlerhafte ID
  /todo-list:  
    post:
      summary: TodoList hinzufügen
      description: ...
      operationId: postList
      responses:
        '200':
          description: TodoList hinzugefügt
    get:
      summary: Alle Listen anzeigen
      description: ...
      operationId: getAllLists
      responses:
        '200':
          description: Alle Listen anzeigen
          content: 
            application/json: 
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/list/properties/id"
          
  /todo-list/{list_id}/entry:
    post:
      summary: Eintrag hinzufügen
      description: ...
      operationId: postEntry
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Eintrag hinzugefügt  
        '404':
          description: Fehlerhafte ID
        '400':
          description: Fehlerhafte Daten
  
  /todo-list/{list_id}/entry/{entry_id}:
    get:
      summary: Eintrag anzeigen
      description: ...
      operationId: getEntry
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
        - in: path
          name: entry_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Eintrag angezeigt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entry'
        '404':
          description: Fehlerhafte ID
    delete:
      summary: Eintrag löschen
      description: ...
      operationId: deleteEntry
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
        - in: path
          name: entry_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Eintrag gelöscht
        '404':
          description: Fehlerhafte ID
    put:
      summary: Eintrag bearbeiten
      description: ...
      operationId: putEntry
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
        - in: path
          name: entry_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Eintrag bearbeitet
        '404':
          description: Fehlerhafte ID
        '400':
          description: Fehlerhafte Daten
components:
  schemas:
    entry:
      type: object
      properties:
        Titel:
          type: string
        Ersteller:
          type: string
        id:
          type: string
        ListID:
          type: string
    list:
      type: object
      properties:
        id:
          type: string
        Name:
          type: string
        Entries:
          type: array
          items: 
            $ref: "#/components/schemas/entry"
          
          
          
          